########################
# directories:
#     dataDirectory: '../../data'
#     #Import directory
#     importDirectory: '../../data/imports'
#     #Archive directory
#     archiveDirectory: '../../data/archive'
#     #Stats directory
#     statsDirectory: '../../data/imports/stats'
#     #databases import diretory
#     databasesDirectory: '../../data/imports/databases'
#     #ontologies import diretory
#     ontologiesDirectory: '../../data/imports/ontologies'
#     #curated import directory
#     curatedDirectory: '../../data/imports/curated'
#     #temp directory
#     tmpDirectory: '../../data/tmp'
#     #Downloads directory
#     downloadsDirectory : '../../data/downloads'

separator: '|'


cypher_queries_file: 'cypher.yml'

usersFile: 'CKG_users.xlsx'

statsFile: 'stats.hdf'
statsCols: 
    - 'date'
    - 'time'
    - 'dataset'
    - 'filename'
    - 'file_size'
    - 'Imported_number'
    - 'Import_type'
    - 'name'
    - 'updated_on'

# sub-graph
graph: 
    - ontologies
    - genes
    - proteins
    - annotations
    - modified_proteins
    - ppi
    - diseases
    - jensenlab
    - protein_structure
    - pathway

#Imports 
ontology_entities: 
    - 'Disease'
    - 'Tissue'
    - 'Biological_process'
    - 'Molecular_function'
    - 'Cellular_component'
    - 'Modification'


#Database resources
#Modified proteins
modified_proteins_resources:
    - 'signor'

#Protein-protein interactions
curated_PPI_resources:
    - 'IntAct'

PPI_action_resources:
    - 'STRING'

#Disease associations
disease_resources: 
    - ['Protein','DisGEnet']

#Pathways
pathway_resources:
    - 'Reactome'
    - 'SMPDB'

#Internal Databases entities
jensenlabEntities:
    - ['Protein','Disease']
    - ['Protein', 'Tissue']
    - ['Protein','Cellular_component']


