version: 1.0
#Database configuration
db_url: "10.18.155.13"
db_port: 7688
db_user: "neo4j"
db_password: "Neo4j"

kg_directory: "tasks/utils/kg"
kg_data_path: "data/bioKG"
imports_databases_directory: "databases"
imports_ontologies_directory: "ontologies"
graphdb_connector_log: "result/bioKG/graphdb_connector_log.config"
graphdb_builder_log: "result/bioKG/graphdb_builder_log.config"
