import: definition.yaml

concurrency:
  task:
    kg-std: 5
  agent:
    gpt-3.5-turbo-0613: 5
    # gpt-4: 2
    # glm-4: 5
    # local_model: 5

assignments:
  - agent:
      - gpt-3.5-turbo-0613
      # - gpt-4
      # - glm-4
      # - local_model

    task:
      - kg-std

output: "results/kgqa/{TIMESTAMP}"