version: 1.0
ckg_directory: "/root/CKG/ckg"
data_directory: "/root/CKG/data"
archive_directory: "/root/CKG/data/archive"
databases_directory: "/root/CKG/data/databases"
experiments_directory: "/root/CKG/data/experiments"
ontologies_directory: "/root/CKG/data/ontologies"
users_directory: "/root/CKG/data/users"
stats_directory: "/root/CKG/data/stats"
downloads_directory: "/root/CKG/data/downloads"
reports_directory: "/root/CKG/data/reports"
tmp_directory: "/root/CKG/data/tmp"
imports_directory: "/root/CKG/data/imports"
imports_databases_directory: "/root/CKG/data/imports/databases"
imports_experiments_directory: "/root/CKG/data/imports/experiments"
imports_ontologies_directory: "/root/CKG/data/imports/ontologies"
imports_users_directory: "/root/CKG/data/imports/users"
imports_curated_directory: "/root/CKG/data/imports/curated"
log_directory: "/root/CKG/log"
report_manager_log: "/root/CKG/ckg/config/report_manager_log.config"
graphdb_connector_log: "/root/CKG/ckg/config/graphdb_connector_log.config"
graphdb_builder_log: "/root/CKG/ckg/config/graphdb_builder_log.config"
analytics_factory_log: "/root/CKG/ckg/config/analytics_factory_log.config"
